on:
  pull_request:
    branches: [main]

env:
  API_KEY: ${{ secrets.BACKSLASH_API_KEY }}
  GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Alternativley you can use a dedicated token


jobs:
  backslash_scan_job:
    runs-on: ubuntu-latest
    name: Backslash scan
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Backslash scan step
        uses: backslash-security/scan-action@main
        with:
          authToken: ${{ env.API_KEY }}
          prScan: true
          githubToken: ${{ env.GITHUB_ACCESS_TOKEN }} # Optional for PR comments
