on:
  pull_request:
    branches: [main]

jobs:
  backslash_scan_job:
    runs-on: ubuntu-latest
    name: Backslash scan
    steps:
      - name: Backslash scan step
        id: bscan
        uses: backslash-security/scan-action@main
        with:
          authToken: ${{ secrets.BACKSLASH_AUTH_TOKEN }}
          ignoreBlock: false
          scanPr: true
          disablePrComments: false
          githubToken: ${{ secrets.GITHUB_TOKEN }}
